title: Hema Iyer
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="docs/Hema Resume Jan 2024.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/hema-iyer-5b2a73a4/">LinkedIn</a> |
  <a href="https://hemaiyer18.github.io/portfolio/">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>

theme: jekyll-theme-minimal
