title: Hema Iyer
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="docs/Hema Resume Jan 2024.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/hema-iyer-5b2a73a4/">LinkedIn</a> |
  <a href="https://hemaiyer18.github.io/portfolio/">GitHub</a>
  
  <br>   
  I'm working as Scrum Master/Agile coach for the past 6 years and |
  Have experience in various Agile Methodologies |
  I am SAFe Agilist, SFe Advanced Scrum Master, PSM-I and PSM-II certified.
  <br>
  </p>

theme: jekyll-theme-minimal
